import { Server } from "./server.types";

export const dummyServerList: Server[] = [
    {
      id: 1,
      title: "Web Server 1",
      description: "Main web server for the company website",
      status: "Online",
      health: "Healthy",
      ipAddress: "192.168.1.101",
      location: "Data Center A",
      owner: "IT Department",
      cpuUsage: "15%",
      memoryUsage: "32%",
      storageUsage: "50%",
      os: "Linux",
      updatedAt: "2023-10-14T08:30:00Z",
    },
    {
      id: 2,
      title: "Database Server",
      description: "Primary database server for customer data",
      status: "Online",
      health: "Healthy",
      ipAddress: "192.168.1.102",
      location: "Data Center B",
      owner: "Database Team",
      cpuUsage: "10%",
      memoryUsage: "25%",
      storageUsage: "70%",
      os: "Windows Server",
      updatedAt: "2023-10-14T09:15:00Z",
    },
    {
      id: 3,
      title: "Mail Server",
      description: "Email server for internal communication",
      status: "Offline",
      health: "Critical",
      ipAddress: "192.168.1.103",
      location: "Data Center C",
      owner: "Email Team",
      cpuUsage: "0%",
      memoryUsage: "90%",
      storageUsage: "85%",
      os: "Linux",
      updatedAt: "2023-10-14T10:45:00Z",
    },
    {
      id: 4,
      title: "Application Server",
      description: "Server for hosting company applications",
      status: "Deployment Pending",
      health: "Pending",
      ipAddress: "192.168.1.104",
      location: "Data Center D",
      owner: "App Team",
      cpuUsage: "0%",
      memoryUsage: "0%",
      storageUsage: "0%",
      os: "Windows Server",
      updatedAt: "2023-10-14T11:30:00Z",
    },
    {
      id: 5,
      title: "Maintenance Server",
      description: "Server under maintenance",
      status: "Maintenance",
      health: "Healthy",
      ipAddress: "192.168.1.105",
      location: "Data Center E",
      owner: "Maintenance Team",
      cpuUsage: "5%",
      memoryUsage: "10%",
      storageUsage: "20%",
      os: "Linux",
      updatedAt: "2023-10-14T12:15:00Z",
    },
  ];
  